databricks_profile:
  target: databricks
  outputs:
    databricks:
      type: databricks
      schema: default
      method: http
      host: "{{ env_var('HOST_PATH') }}"
      http_path: CLUSTER_HTTP_PATH
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"